# Numpy  indexing and selection

In [1]:
import numpy as np


In [2]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0]

0

In [6]:
arr[:4]

array([0, 1, 2, 3])

In [7]:
arr[0:3]

array([0, 1, 2])

In [8]:
arr[0:3]=100

In [9]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [10]:
#so cant copy the data directly  becasue numpy copy all data,to save memory in numpy
# to avoid this we can use copy function 
# see the ecamplt
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [11]:
new_arr=arr

In [12]:
new_arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [13]:
new_arr[0:3]=109

In [14]:
new_arr

array([109, 109, 109,   3,   4,   5,   6,   7,   8,   9,  10])

In [15]:
arr # se data is changed here as well

array([109, 109, 109,   3,   4,   5,   6,   7,   8,   9,  10])

In [16]:
# use copy for this thing
arr

array([109, 109, 109,   3,   4,   5,   6,   7,   8,   9,  10])

In [18]:
new=arr.copy()

In [19]:
new

array([109, 109, 109,   3,   4,   5,   6,   7,   8,   9,  10])

In [20]:
new[0:4]=400

In [21]:
new

array([400, 400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [22]:
arr #se nnow the data is not chanaged

array([109, 109, 109,   3,   4,   5,   6,   7,   8,   9,  10])

In [23]:
# 2 d array

In [25]:
new2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
new2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
new2d[0][0]

1

In [28]:
new2d[0]


array([1, 2, 3])

In [29]:
#CONDITIONAL SELECTION

In [30]:
again=np.arange(1,22)

In [31]:
again


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [32]:
again >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [33]:
# it si conditional check and will retuurnboolean reslt
result=again >4

In [34]:
again[result]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [35]:
again[again >4] # same reuslt

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [38]:
again[again<6]

array([1, 2, 3, 4, 5])

In [40]:
#numpy opration

In [42]:
#array eith array
# array with scaler
# array with universal function

In [43]:
arr=np.arange(0,11)

In [44]:
arr+arr  #addition of array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr *arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [48]:
#scaler meean  single value in mathematicd

In [49]:
arr+20.1

array([20.1, 21.1, 22.1, 23.1, 24.1, 25.1, 26.1, 27.1, 28.1, 29.1, 30.1])

In [51]:
arr/0

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [53]:
 # 0/0 will give NaN and 1/0 will give infinity

In [54]:
arr**3  #cube of integer value

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [55]:
np.sqrt(25)

5.0

In [56]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [57]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [58]:
arr.max()

10

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [62]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [63]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [65]:
#tan=sin/cos

# Pandas


In [66]:
# pandas can work on different wide variety of sources
# it is built on top of numpy
#it allow faster analysis and data cleaning and preparation
#it also has built in features

In [74]:
#series object in pandas
list=['a','b','c']
number=[10,20,30]
dict={1:"a",2:"bb"}

import pandas as pd
pd.Series(list)

0    a
1    b
2    c
dtype: object

In [71]:
pd.Series(number)

0    10
1    20
2    30
dtype: int64

In [72]:
pd.Series(dict)

1     a
2    bb
dtype: object

In [75]:
pd.Series(data=number,index=list)   # putting the labels

a    10
b    20
c    30
dtype: int64

In [76]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
# pandas hold differnt kind of object type

In [77]:
ser=pd.Series([10,20,30,40],["A","B","C","D"])

In [78]:
ser

A    10
B    20
C    30
D    40
dtype: int64

In [79]:
ser1=pd.Series([10,20,30,40],["A","F","C","D"])
ser1

A    10
F    20
C    30
D    40
dtype: int64

In [80]:
ser+ser1  # it took all the cobination , whicever is matched it will be added and rest eill be NaN

A    20.0
B     NaN
C    60.0
D    80.0
F     NaN
dtype: float64

In [81]:
ser["A"]

10

In [82]:
ser.A # same thing

10

In [83]:
  #Dataframes

In [84]:
from numpy.random import randn

In [90]:
df=pd.DataFrame(randn(4,6),index=["a","b","c","d"],columns=["a","b","c","d","e","f"])

In [91]:
df

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [92]:
df.a   # a is a column name

a   -0.625339
b   -1.192377
c   -0.229449
d    1.165219
Name: a, dtype: float64

In [93]:
df["a"] # same thing

a   -0.625339
b   -1.192377
c   -0.229449
d    1.165219
Name: a, dtype: float64

In [94]:
type(df["a"]) # it is actually daing it is  a series 

pandas.core.series.Series

In [95]:
type(df)  # it is datframe

pandas.core.frame.DataFrame

In [97]:
df[["a","b"]]  #we need to provide list of it

a         b
a -0.625339 -0.646107
b -1.192377  0.633142
c -0.229449  0.587135
d  1.165219  0.286136

In [99]:
df.index[0]

'a'

In [100]:
df.index[0:4]

Index(['a', 'b', 'c', 'd'], dtype='object')

In [101]:
df.index[0:100]

Index(['a', 'b', 'c', 'd'], dtype='object')

In [104]:
df["new_column"]  # it will give error so it mean their is no column name or key name is new_column

KeyError: 'new_column'

In [105]:
df["new_column"]=df["a"]  #created new column

In [106]:
df

a         b         c         d         e         f  new_column
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103   -0.625339
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476   -1.192377
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928   -0.229449
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443    1.165219

In [107]:
df["new_column"]=df["a"]+df["b"]

In [109]:
df # new column is modified


a         b         c         d         e         f  new_column
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103   -1.271446
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476   -0.559235
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928    0.357687
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443    1.451354

In [111]:
# i eant to drop column new_column then we can use  drop methos
df.drop("new_column")  # by default axis=0 , its mean it is refering to index 

KeyError: "['new_column'] not found in axis"

In [112]:
df.drop("new_column",axis=1)

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [113]:
df  # action is not permanent for that  use assignment

a         b         c         d         e         f  new_column
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103   -1.271446
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476   -0.559235
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928    0.357687
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443    1.451354

In [114]:
df=df.drop("new_column",axis=1)

In [115]:
df  # now it is permanent  
# or we can use inplace parameter which presntin drop methos ,if it is Truwe then  vcanges are sucessfull
#otherwise it wil give not save the election

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [116]:
# now delete row

In [117]:
df.drop("d")   # if column name are same as index then it bydefault  it will pic row or index 
# which is great

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928

In [119]:
df.shape   # it is t tuple  4 measn row , it is showing showing 4 beacuse i havnt use inplace parameter in previous drop method

(4, 6)

In [125]:
# extracting the row by sung loc method
df.loc["a"]

a   -0.625339
b   -0.646107
c   -1.551139
d    0.635770
e   -0.041102
f    0.891103
Name: a, dtype: float64

In [126]:
df.loc[["a","B"]]  # in this i use upper casee letter B but look at the output it provide extra row with NaN value

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


a         b         c        d         e         f
a -0.625339 -0.646107 -1.551139  0.63577 -0.041102  0.891103
B       NaN       NaN       NaN      NaN       NaN       NaN

In [127]:
df.loc[["a","b"]]  # now it is showing correct value
# in this r need to provide index name

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476

In [130]:
#but in iilocwe need to provide index location or index value , let see in example
df.iloc[0]  # 0 index

a   -0.625339
b   -0.646107
c   -1.551139
d    0.635770
e   -0.041102
f    0.891103
Name: a, dtype: float64

In [131]:
# we can fetech perticualr value as well
df.loc["a","a"]  # it fetech [0][0] value in 2 d array

-0.6253387078525111

In [132]:
df

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [133]:
# we can extract subset of columnor row
df.loc[["a","b"],["e","f"]] # looks perfext

e         f
a -0.041102  0.891103
b  1.392532 -0.241476

In [134]:
# conditional selection
# means to check certain condition and it will give boolean value

In [135]:
df>0

a      b      c     d      e      f
a  False  False  False  True  False   True
b  False   True   True  True   True  False
c  False   True   True  True   True  False
d   True   True  False  True  False   True

In [136]:
a=df>0

In [138]:
df[a] # nan for false value

a         b         c         d         e         f
a       NaN       NaN       NaN  0.635770       NaN  0.891103
b       NaN  0.633142  1.212738  0.782465  1.392532       NaN
c       NaN  0.587135  1.752333  0.648224  0.260028       NaN
d  1.165219  0.286136       NaN  0.963765       NaN  0.574443

In [139]:
df[df>0] # same thing but efficeient 

a         b         c         d         e         f
a       NaN       NaN       NaN  0.635770       NaN  0.891103
b       NaN  0.633142  1.212738  0.782465  1.392532       NaN
c       NaN  0.587135  1.752333  0.648224  0.260028       NaN
d  1.165219  0.286136       NaN  0.963765       NaN  0.574443

In [140]:
df[df["a"]>0]  # other was NaN or faslr or donesnot match the criteria

a         b         c         d         e         f
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [142]:
df[df["b"]>0] 

a         b         c         d         e         f
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [143]:
df[df["b"]>0]["b"]

b    0.633142
c    0.587135
d    0.286136
Name: b, dtype: float64

In [144]:
df[df["b"]>0]["c"] # extrating column

b    1.212738
c    1.752333
d   -2.375859
Name: c, dtype: float64

In [145]:
df[df["b"]>0][["c","a"]] # multiple column

c         a
b  1.212738 -1.192377
c  1.752333 -0.229449
d -2.375859  1.165219

In [146]:
True and True

True

In [147]:
True and False

False

In [148]:
False and False

False

In [149]:
False and True

False

In [153]:
df[(df["b"]>0) & (df["b"]>1)]  # no matching result thats why

Empty DataFrame
Columns: [a, b, c, d, e, f]
Index: []

In [154]:
df[(df["b"]>0) | (df["b"]>1)]  # or opearation in it

a         b         c         d         e         f
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [155]:
df

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [156]:
df.reset_index()  # new index allocation in it
# this is not permanent becasue we havnt usr inplacr parameter i n it

index         a         b         c         d         e         f
0     a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
1     b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
2     c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
3     d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [170]:
list=["aj","su","ajr","sru"] # took 2 min to write it down


In [158]:
list

['aj', 'su', 'ajr', 'sru', 'agj', 'sgu']

In [171]:
code="aj su th rs ".split() # took less than 30 sec 
# now on i will use split method to dplit it and it will automatically converete into string


In [172]:
code

['aj', 'su', 'th', 'rs']

In [173]:
df["country"]= code  # ahowing wrroe becasu length does not match


In [169]:
df

a         b         c         d         e         f
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [174]:
df["country"]= code

In [175]:
df

a         b         c         d         e         f country
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103      aj
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476      su
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928      th
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443      rs

In [176]:
df.set_index("country")

a         b         c         d         e         f
country                                                            
aj      -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103
su      -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476
th      -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928
rs       1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443

In [178]:
df  # not permanent yet bacraue of inplace parameter

a         b         c         d         e         f country
a -0.625339 -0.646107 -1.551139  0.635770 -0.041102  0.891103      aj
b -1.192377  0.633142  1.212738  0.782465  1.392532 -0.241476      su
c -0.229449  0.587135  1.752333  0.648224  0.260028 -1.198928      th
d  1.165219  0.286136 -2.375859  0.963765 -0.203629  0.574443      rs

In [179]:
# missing data
d={"A":[1,2,np.nan],"B":[5,np.nan,np.nan],"C":[1,2,3]}


In [180]:
d  # this is normal dictionary look like

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [182]:
pd.DataFrame(D)

NameError: name 'D' is not defined

In [187]:
df=pd.DataFrame(d)
# it automatically show value in floats

In [188]:
df.dtypes

A    float64
B    float64
C      int64
dtype: object

In [189]:
df


A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [190]:
# it will delete att the row if it found any NaN in it
df.dropna()  #it si working as in axis is row 

A    B  C
0  1.0  5.0  1

In [191]:
df.dropna(axis=1) # now it will work on column

C
0  1
1  2
2  3

In [192]:
df.dropna(thresh=2)  # we have provided threhhold value

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [193]:
# we can fill vaue or emplty value in our data with the help of fillna method
df.fillna(value="fill value")

A           B  C
0           1           5  1
1           2  fill value  2
2  fill value  fill value  3

In [194]:
# we canput the mean value in it
df["A"].fillna(value=df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [195]:
# group by in pandas
#groupby allow you to group together roes based off  of a column and perform an aggregate function on them

In [205]:
#lets create a dictionary
data={"Company":["google","google","apple","apple","facebook"],
     "person":["sam","charles","janes","amk","oak"],
     "sales":[200,100,130,34,100]}
pd.Series(data)  # series represtation and it is doesnt look good

Company    [google, google, apple, apple, facebook]
person              [sam, charles, janes, amk, oak]
sales                      [200, 100, 130, 34, 100]
dtype: object

In [206]:
df=pd.DataFrame(data)

In [207]:
# lets groupby them
# but keep in mind  it will not show output when we create group_by in it
group=df.groupby("Company")

In [208]:
group  # dataframe is created

In [209]:
group.max()

person  sales
Company               
apple     janes    130
facebook    oak    100
google      sam    200

In [211]:
group.mean()  # itexcluded person column becasue panda automatically see that it does not have necassary information

sales
Company        
apple        82
facebook    100
google      150

In [212]:
group.min()  # early in alphabet

person  sales
Company                 
apple         amk     34
facebook      oak    100
google    charles    100

In [213]:
group.sum()

sales
Company        
apple       164
facebook    100
google      300

In [215]:
group.std() #standard devation

sales
Company            
apple     67.882251
facebook        NaN
google    70.710678

In [217]:
group.sum()

sales
Company        
apple       164
facebook    100
google      300

In [218]:
group.sum().loc["google"]  # to give perticualr location

sales    300
Name: google, dtype: int64

In [219]:
df.groupby("Company").sum().loc["google"]  # all in one with result ,looks effective

sales    300
Name: google, dtype: int64

In [220]:
df.groupby("Company").count()

person  sales
Company                
apple          2      2
facebook       1      1
google         2      2

In [222]:
df.groupby("Company").describe()  # multipe things

sales                                                     
         count   mean        std    min    25%    50%    75%    max
Company                                                            
apple      2.0   82.0  67.882251   34.0   58.0   82.0  106.0  130.0
facebook   1.0  100.0        NaN  100.0  100.0  100.0  100.0  100.0
google     2.0  150.0  70.710678  100.0  125.0  150.0  175.0  200.0

In [224]:
df.groupby("Company").describe().transpose()  # to transpose the result

Company           apple  facebook      google
sales count    2.000000       1.0    2.000000
      mean    82.000000     100.0  150.000000
      std     67.882251       NaN   70.710678
      min     34.000000     100.0  100.000000
      25%     58.000000     100.0  125.000000
      50%     82.000000     100.0  150.000000
      75%    106.000000     100.0  175.000000
      max    130.000000     100.0  200.000000

In [225]:
# merging and joining 
# see from other pandas

In [228]:
# operation  in pandas
df=pd.DataFrame({"Col1":[1,2,3,4],
                "Col2":[444,555,666,777],
                 "col3":["abc","cda","xyz","vbg"]})

In [229]:
df


Col1  Col2 col3
0     1   444  abc
1     2   555  cda
2     3   666  xyz
3     4   777  vbg

In [230]:
df.head()

Col1  Col2 col3
0     1   444  abc
1     2   555  cda
2     3   666  xyz
3     4   777  vbg

In [232]:
df["Col2"].unique

<bound method Series.unique of 0    444
1    555
2    666
3    777
Name: Col2, dtype: int64>

In [234]:
len(df["Col2"].unique())


4

In [236]:
df["Col2"].unique() # correct way to write it down

array([444, 555, 666, 777], dtype=int64)

In [237]:
df["Col2"].nunique() # same result as len function

4

In [240]:
df["Col2"].value_counts()

444    1
555    1
666    1
777    1
Name: Col2, dtype: int64

In [242]:
df["Col1"]


0    1
1    2
2    3
3    4
Name: Col1, dtype: int64

In [244]:
df["Col1"].apply(times2) # it should work 

NameError: name 'times2' is not defined

In [246]:
df["Col1"].apply(lambda x:x*10) #lambda function

0    10
1    20
2    30
3    40
Name: Col1, dtype: int64

In [247]:
df.columns

Index(['Col1', 'Col2', 'col3'], dtype='object')

In [248]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [249]:
df

Col1  Col2 col3
0     1   444  abc
1     2   555  cda
2     3   666  xyz
3     4   777  vbg

In [250]:
df.sort_values("col3") #  by deafult it is ascending
# index is also same

Col1  Col2 col3
0     1   444  abc
1     2   555  cda
3     4   777  vbg
2     3   666  xyz

In [251]:
df.sort_values(by="col3") # same thing

Col1  Col2 col3
0     1   444  abc
1     2   555  cda
3     4   777  vbg
2     3   666  xyz

In [252]:
df.isnull()

Col1   Col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False