In [ ]:
# confusion metrics is the simplest metrics to find out the accuracy and correctness of the classification model
# what is classification 

# classifcation is a supervised machine learning technique
# like survival rate , wheter he live or not 2
# for iris we have 3
# for spam , we have 4(promotion,social,spam,legimate)

# cofusion metrics is also called error metrics
# each row represnt actua data
#each column represent predictrion

            predicted value
actual values  0 -ve  1 +ve
        0     25(TN)  15(FP)
        1     30(Fn)  80(Tp)
        
#00 true
#11 true
#01 10 false

# this is 2 *2 reprenstaton
        
#classification model correctly found 25 which are incorrect


from sklearn.metrics import confusion_matrix
confusion_metrix(y,y_pred)





# what is type 1 and type 11 error in confusion matrix
# it is nothing but the false negative and false positive
#FP and FN


# fasle positive is type 1 error
# fasle negative is type 11 error



# false positive if false true   --type 1
# faasle nefative is false false --type11



# what is accuracy
# 
            predicted value
actual values  0 -ve  1 +ve
        0     40      10
        1     5      95
        n=150
        
accuracy =correctly predicted/total
         = 40+95/150
        =0.9
        
error rate=error/total
        =10+5/150
    
#or we can do one more thing    1-accuracy=error rate





# now we will discuss rate 
   0   1
0  47  3
1  5   45

TPR=45/45+5  =0.9
TNR=47/47+3  =0.94
FPR=3/47+3   =0.06
FNR=5/45+5   =0.01




#Lets take an another example
 
x(Actual)   x'(predicted)
1           1
1           1
1           1
1           1
0           1
1           0
0           0
0           0


        predicted
    1           0
1   4           1
0   1           2



# Feature scaling


In [ ]:
#Feature Scaling or Standardization: It is a step of Data Pre Processing which is applied to independent variables or
 #   features of data. It basically helps to normalise the data within a particular range. Sometimes,
 #   it also helps in speeding up the calculations in an algorithm. Package Used: sklearn.preprocessing

In [1]:
from sklearn import preprocessing

In [3]:
import numpy as np
x=np.array([[-400],[-100],[0],[100],[400]])

In [4]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [5]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))

In [7]:
x_scaler=minmax.fit_transform(x)

In [8]:
x_scaler   # it represnt the value betweeen 0 to 1

array([[0.   ],
       [0.375],
       [0.5  ],
       [0.625],
       [1.   ]])

In [ ]:
#Note that, by default, it transforms the data into a range between 0 and 1 (-1 and 1, if there are negative values).
#It can be used as an alternative to The Standard Scaler or when the data is not normally distributed

In [9]:
minmax=preprocessing.MinMaxScaler(feature_range=(10,11))
x_scaler=minmax.fit_transform(x)
x_scaler ## now i have chge the value

array([[10.   ],
       [10.375],
       [10.5  ],
       [10.625],
       [11.   ]])

In [ ]:
#feature scaling formula
(xi-xmin)/(xmax-xmin)

lets use   minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

(-400-(-400))/(400-(-400))
0/800
0
#so the value is 0



# feature scaling by Standardscaler

In [11]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

In [12]:
standard=preprocessing.StandardScaler()
x_scalar=standard.fit_transform(x)
x_scalar

# it look like value is from -1 to 1

array([[-1.53392998],
       [-0.38348249],
       [ 0.        ],
       [ 0.38348249],
       [ 1.53392998]])

In [ ]:
#formula  is
(x1-xmean)/(standard devaition of the feature)


# feature scaling from normalizer

In [15]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

normalizer=preprocessing.Normalizer()
x_scalar=normalizer.fit_transform(x)
x_scalar

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

# feature scaling from Binarizer

In [16]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

Binarizer=preprocessing.Binarizer()
x_scalar=Binarizer.fit_transform(x)
x_scalar

array([[0],
       [0],
       [0],
       [1],
       [1]])

# feature scaling from MaxAbsScaler

In [17]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

MaxAbsScaler=preprocessing.MaxAbsScaler()
x_scalar=MaxAbsScaler.fit_transform(x)
x_scalar

array([[-1.  ],
       [-0.25],
       [ 0.  ],
       [ 0.25],
       [ 1.  ]])

# Feature scaling from RobustScaler

In [19]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-300],[-200],[-100],[-50],[0],[100],[400]])

RobustScaler=preprocessing.RobustScaler()
x_scalar=RobustScaler.fit_transform(x)
x_scalar

array([[-1.3],
       [-0.9],
       [-0.5],
       [-0.1],
       [ 0.1],
       [ 0.3],
       [ 0.7],
       [ 1.9]])

In [ ]:
#using inverse_transform to get bak out previous  data

In [26]:
from sklearn import preprocessing 
import numpy as np

x=np.array([[-400],[-300],[-200],[-100],[-50],[0],[100],[400]])

standard=preprocessing.StandardScaler()
x_scalar=standard.fit_transform(x)
x_scalar






array([[-1.42105964],
       [-0.9920605 ],
       [-0.56306137],
       [-0.13406223],
       [ 0.08043734],
       [ 0.29493691],
       [ 0.72393604],
       [ 2.01093345]])

In [28]:
x_scalar_transform=standard.inverse_transform(x_scalar)
x_scalar_transform

array([[-400.],
       [-300.],
       [-200.],
       [-100.],
       [ -50.],
       [   0.],
       [ 100.],
       [ 400.]])