In [1]:
1


1

In [2]:
2.0

2.0

In [3]:
3

3

In [4]:
1/1 # it give floating result

1.0

In [5]:
name_of_variable=12

In [6]:
name_of_variable

12

In [7]:
#string
"hi i am using anaconda for runnig python code"

'hi i am using anaconda for runnig python code'

In [8]:
'using sngle cotes'

'using sngle cotes'

#   Numpy 

In [ ]:
#Numpy is a Linear Algebra library for python 
#most of other library used numpy 
# numpy is fast and it is binding to c libraary
# nupmpy has two things vector and matrix
#vector are one d array
# matrx are 2d array

In [9]:
#Numpy array
list=[1,2,3,4,5] # thats a vector or 1 d array

In [10]:
import numpy as np # casting list into array
np.array(list)

array([1, 2, 3, 4, 5])

In [11]:
#2 d array
two_d=[[1,2,3],[3,4,5]]
two_d

[[1, 2, 3], [3, 4, 5]]

In [12]:
np.array(two_d)

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
two_d=[[1,2,3,3],[3,4,5]]
two_d

[[1, 2, 3, 3], [3, 4, 5]]

In [14]:
np.array(two_d)  # it still executed although  i have provided extra digit

array([list([1, 2, 3, 3]), list([3, 4, 5])], dtype=object)

In [15]:
# everytime we donot need list to put some value in numpy, we can use arange function in it
np.arange(1,4)

array([1, 2, 3])

In [16]:
np.arange(1,4,1) # by default it work like this , so no need  of putting value in ot

array([1, 2, 3])

In [17]:
np.arange(1,4,2)

array([1, 3])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((3,3))  # sanme outpput

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,4)  # o to 5 with 4 value

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [28]:
np.random.rand(3) # 3 random numbers

array([0.05794766, 0.83291815, 0.31049846])

In [29]:
np.random.rand(3,3)

array([[0.75938401, 0.39998069, 0.0741633 ],
       [0.1848451 , 0.44082442, 0.9078597 ],
       [0.2414247 , 0.73013767, 0.37286493]])

In [30]:
np.random.randn(3) # 3 number from standard normal distribution

array([0.74913225, 1.80249235, 0.39216214])

In [31]:
np.random.randint(1,10)  # it gice integer from 1 to 10

8

In [33]:
np.random.randint(1,10,4) # four random number

array([7, 9, 6, 2])

In [34]:
#reshaepe function
arr=np.arange(25)
arr.reshape(5,5)  # value should be equal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr  # it is showing original shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.max()

24

In [37]:
arr.min()

0

In [39]:
arr.mean()

12.0

In [40]:
arr.min()

0

In [42]:
arr.dtype

dtype('int32')

In [43]:
arr.argmax() # it is showing the index the location

24

In [45]:
arr.argmin  # 0 index 

0

In [47]:
arr.shape  # it si one d array with 25 element in it

(25,)

In [48]:
from numpy.random import randint

In [50]:
randint(2,19)

2